DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS (
    ID VARCHAR(36) NOT NULL PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL,
    SURNAMES VARCHAR(255) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    PASSPORT_NUMBER VARCHAR(24) NOT NULL,
    ENROLLMENT_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
    ACTIVE BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX I_CUSTOMERS_01 ON CUSTOMERS(PASSPORT_NUMBER);