jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Spotless Check
        run: mvn spotless:check

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Run Tests
        run: mvn test

      - name: Build with Maven
        run: mvn package -DskipTests

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/travel-agency:${{ github.sha }} .
          docker save ${{ secrets.DOCKER_HUB_USERNAME }}/travel-agency:${{ github.sha }} > image.tar

      - name: Upload Docker Image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar

  push_image:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download Docker Image
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      - name: Load Docker Image
        run: docker load -i image.tar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/travel-agency:${{ github.sha }}
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/travel-agency:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/travel-agency:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/travel-agency:latest