name: Java CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Spotless Check
        run: mvn spotless:check

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Run Tests
        run: mvn test

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/travel-agency:${{ github.sha }} .

      - name: Save Docker Image
        uses: actions/upload-artifact@v3
        with:
          name: docker-image-${{ github.sha }}
          path: . # Assuming Dockerfile is in the root

  push_image:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only run on pushes to main
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: docker-image-${{ github.sha }}
          path: .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push to Docker Hub
        run: |
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/travel-agency:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/travel-agency:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/travel-agency:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/travel-agency:latest

      - name: Trigger Render Deployment
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_WEBHOOK }}&imgURL=docker.io%2F${{ secrets.DOCKER_HUB_USERNAME }}%2Ftravel-agency%3A${{ github.sha }}"