name: Java CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/travel-agency:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/travel-agency:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/travel-agency:latest
          docker image ls  # Para verificar que la imagen existe

  push_image:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/travel-agency:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/travel-agency:latest


